### PR TITLE
fix(dependencies): move publish-please to devDeps since it's only needed for maintainers of this package

### PR DESCRIPTION
**Pull request by PeledYuval**
## Description
cli-table's latest changes break downstream builds due to publish-please being in its dependencies. Since publish-please is only required for the maintainers of this package, a good solution is to move it to this package's dev dependencies.

This PR fixes this issue:
https://github.com/Automattic/cli-table/issues/129

### CODE REVIEW

**Review by orizis — APPROVED** [review]

**Comment by KutnerUri** [comment]
please move all irrelevant deps to devDeps

**Review by joamag — APPROVED** [review]

**Review by saitho — APPROVED** [review]
As KutnerUri suggested all dependencies not required for using it should also be moved to devDependencies (e.g. babel-jest looks like such a module).
Still approving for now since the broader issue with publish-please affecting downstream repos should be fixed with that.

**Comment by PeledYuval** [comment]
@KutnerUri @saitho I moved all relevant dev dependencies to devDependencies, please take another look

**Review by saitho — APPROVED** [review]

**Review by chrean — APPROVED** [review]
Thanks for submitting and sorry for all the hassle, my bad!

**Comment by PeledYuval** [comment]
@chrean Is it possible to delist the broken version from npm to force all builds to use a different version? This would automagically fix a lot of builds without people needing to commit a new package-lock for them.

**Comment by chrean** [comment]
Sure, will do ASAP!

**Comment by PeledYuval** [comment]
Thanks!

**Comment by chrean** [comment]
@PeledYuval 0.3.2 has been deprecated.

**Comment by atao60** [comment]
The broken version is the 0.3.3 not the 0.3.2
See https://www.npmjs.com/package/cli-table?activeTab=versions

**Comment by chrean** [comment]
@atao60 0.3.3 has been deprecated as well.
0.3.4 should be used now.

**Comment by chrean** [comment]
Will keep an eye on this PR next few hours to make sure everything is back to normal.
Sorry again for all the issues.

**Pull request merged**
