### PR TITLE
fix for KANJI width.

### PR DESCRIPTION
**Pull request by katoy**
Support for KANJI-character, please.

Attached 2 screnn-shot, before-fix and after-fix.
in the before-fix, some cell's width are incorrect.
- before-fix
  before-fix
- after-fix
  after-fix

### CODE REVIEW

**Comment by Leask** [comment]
Why close...

**Comment by rauchg** [comment]
It's not closed

**Comment by rauchg** [comment]
(we want to fix this)

**Comment by Leask** [comment]
I am working on a cli tools with cli-table, and I need this fixed. How can
I help?

**Comment by Leask** [comment]
The unicode-eastasianwidth way may help!? Why don't you merge it?

**Comment by GaryJones** [comment]
Still needs a rebase to fix the merge conflicts.

**Comment by tyrasd** [comment]
I believe this was also fixed with #97

**Comment by chrean** [comment]
Fixed with https://github.com/Automattic/cli-table/pull/97 .

**Pull request closed without merging**
