### PR TITLE
Make sure options are not null. Add test

### PR DESCRIPTION
**Pull request by phess101**
## Description

Currently, if you try to create a new Table with no options, you will get a crashing error. We need to first do a null check against options.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [X] This change works and has been tested locally (or has an appropriate fallback).
- [X] This change has relevant unit tests.
- [ ] This change has relevant documentation additions / updates (if applicable).

## Deploy Notes

Notes regarding deployment of this PR, if any.

## Steps to Test or Reproduce

1. Create an instance of Table without any options
2. Verify that your table object is not null, and there were no exceptions thrown

### CODE REVIEW

**Comment by phess101** [comment]
Related to issue https://github.com/Automattic/cli-table/issues/153

**Comment by yjhuoh** [comment]
ha looks like we did the same thing. https://github.com/Automattic/cli-table/pull/155

**Comment by clintecker** [comment]
:+1:

**Comment by clintecker** [comment]
This is currently breaking Google's `firebase-tools` as their dependency is specified as `^0.3.1` :(

**Comment by clintecker** [comment]
I've emailed @chrean, but maybe @igoradamenko or @msabramo could help us out

**Comment by yjhuoh** [comment]
maybe we should just pin the version in `firebase-tools` 🤔

**Comment by mikeendale** [comment]
+1 Please merge

> maybe we should just pin the version in `firebase-tools` 🤔

Created a PR for that too: https://github.com/firebase/firebase-tools/pull/3908

**Pull request merged**
