### PR TITLE
Replace colors.js with chalk

### PR DESCRIPTION
**Pull request by joshbetz**
Chalk is a drop-in replacement for our use-case, but also supports
the bright versions of colors.

Fixes #63

### CODE REVIEW

**Comment by tecfu** [comment]
Hey Josh. Automattic/cli-table is unmaintained and this pull request likely the won't get merged. One alternative that is maintained is tecfu/tty-table

**Comment by Turbo87** [comment]
tecfu/tty-table is GPLv3 though, so unlikely to get used by a lot of companies :-/

**Comment by tecfu** [comment]
@Turbo87 That was changed in https://github.com/tecfu/tty-table/commit/03433b84e68f51e8557e6c6ca825b1276c4a9919 and is reflected in [version 2.6.6](https://www.npmjs.com/package/tty-table).

**Comment by joshbetz** [comment]
I'm working on a new release here.

**Comment by tecfu** [comment]
What features are you adding?

**Pull request merged**
