### PR TITLE
Change version from 0.0.1

### PR DESCRIPTION
**Pull request by LoganDark**
Uses the one from package.json automatically.

### CODE REVIEW

**Comment by LoganDark** [comment]
Preferably, this would be done manually / by an automated process since `require()` is synchronous, but I doubt this will be noticeable, considering `package.json` is only a few KB in size and `require()` keeps a cache.

**Comment by chrean** [comment]
True thing, not sure if automating this is worth the hassle, but we may look into this, low-prio?

**Comment by LoganDark** [comment]
Yeah, that sounds fine.

**Comment by chrean** [comment]
https://github.com/Automattic/cli-table/issues/112

**Pull request merged**
