### PR TITLE
Replaced colors with chalk

### PR DESCRIPTION
**Pull request by ksatirli**
Hello Automattic, 

I replaced [colors.js](https://github.com/marak/colors.js/) with [chalk](https://github.com/sindresorhus/chalk) to make using `cli-table` more joyful. 

`chalk` does not extend built-ins and has seen twice the usage in recent months (as well as being 16th most-popular) when compared to `colors` (61st).

All the tests work (unchanged) as the color values are identical between both modules.

### CODE REVIEW

**Comment by ksatirli** [comment]
I made an update to require an exact version of chalk (1.0.0) but noticed that the builds still fail on node v0.6 and v0.8 due to `chalk` requiring, at the least, node v0.10.0.

If support for v0.6 is required going forward, I'm afraid `chalk` wont work out. Though it is possible for v0.8 to use an older version of `chalk` (0.4.0), I don't like the idea of that a lot. 

Obviously, this is not a decision I can make, so any input would be most welcome!

**Comment by stevenvachon** [comment]
[colors.js](https://github.com/marak/colors.js/) does not extend built-ins if you use the "safe" version, which cli-table *does* use: https://github.com/Automattic/cli-table/blob/master/lib/index.js#L6

**Comment by ksatirli** [comment]
Hi @stevenvachon you're right! I noticed into this after submitting my PR. 

Given this, then, the only reason to use `chalk` would be broader use of the module.

**Comment by stevenvachon** [comment]
Yeah, and as stated earlier, with a cost: less backwards-compatibility.

**Comment by ksatirli** [comment]
@stevenvachon understood! I'll go ahead and close this PR.

**Comment by DanielRuf** [comment]
Can we revisit this PR? colors.js is not maintained or developed anymore.

**Pull request closed without merging**
