### PR TITLE
Added auto-resizing support. Tables now fully responsive.

### PR DESCRIPTION
**Pull request by tecfu**
Column widths now automatically resize when the optioned or calculated width of the columns exceed the width of the terminal viewport. 

This fixes a bug that existed whereby the borders would not render correctly when they did not fit within the terminal viewport. 

This was done by checking the total width of needed by the columns and determining if that width exceeded the width of the terminal viewport. When so, the column widths are resized to equal divisions of the table so that they do not overlap the terminal viewport bounding box.

Also, full text wrapping is implemented rather than the current '...', truncated line solution. This was done using the js-beautify package.

### CODE REVIEW

**Comment by tecfu** [comment]
Also, this fails the unit tests because, of course, you hardcoded in the expected output strings and they don't match the responsive sizing. 

However, I ran through your unit tests, manually checked each for errors and didn't see any problems.

**Comment by stevenvachon** [comment]
Why'd you close this?

**Comment by gabrielcsapo** [comment]
@tecfu yeah can you add this back 🙏

**Comment by tecfu** [comment]
@gabrielcsapo Because these guys don't maintain the package. So I ended up building a new table package from scratch [tty-table](https://github.com/tecfu/tty-table) and I also made it support the Automattic/cli-table API. So there's no reason to use this package any more, other than the fact that its older and has more stars.

**Comment by gabrielcsapo** [comment]
@tecfu i will check it out! Thank you!

**Pull request closed without merging**
