### PR TITLE
Automatic text wrapping, other bugfixes

### PR DESCRIPTION
**Pull request by tecfu**
See commit notes.

### CODE REVIEW

**Comment by stevenvachon** [comment]
I really wonder if anyone involved in this project really cares about maintaining it. PRs never seem to get merged.

**Comment by tecfu** [comment]
@stevenvachon Sent you a pull request.

**Comment by stevenvachon** [comment]
@tecfu I'm not a maintainer of the project

**Comment by tecfu** [comment]
@stevenvachon Ahh...I thought you were implicitly soliciting collaboration...and hence sent a pull request to your fork.

https://github.com/stevenvachon/cli-table/pull/1

**Comment by stevenvachon** [comment]
Nope, I was complaining :)

**Comment by tecfu** [comment]
Well, I see that you've put in 5 commits. As an alternative to just complaining, I'd be happy to work with you and merge your work into mine. I attempted to merge my work into yours as a demonstration that I don't care about the credit taking aspect.

 If you have future development ideas, you call always send me a PR and I will merge it.

**Comment by tecfu** [comment]
Because pull requests on this repo are being ignored and because I found working with the existing code unwieldy - I've published an alternative table package to create the functionality that this package lacks:

https://github.com/tecfu/tty-table

I urge anyone interested in using this PR to use it instead.

**Comment by stevenvachon** [comment]
There's also [cli-table2](https://npmjs.com/cli-table2) (referenced in [#51](https://github.com/Automattic/cli-table/issues/51#issuecomment-67727096)), which was created for the very same reason.

**Comment by stevenvachon** [comment]
My guess is that Automattic just doesn't give a shit about node.js ... pretty asshole'ish to take over a project from someone and ignore those who attempt to improve it.

**Comment by GaryJones** [comment]
Needs a rebase to fix the merge conflicts.

**Pull request closed without merging**
