### PR TITLE
make the string which includes chinese characters has a right length

### PR DESCRIPTION
**Pull request by xincici**

### CODE REVIEW

**Comment by camsong** [comment]
please merge this

**Comment by tecfu** [comment]
I support Chinese characters in my backwards compatible terminal table. Either use mine (http://github.com/tecfu/tty-table) or use cli-table2. This hasn't been actively supported for a long time.

**Comment by xincici** [comment]
@camsong use this instead https://www.npmjs.com/package/cli-table-cjk

**Comment by GaryJones** [comment]
For it to be merged here, the merge conflicts need to be resolved, including not updating the package.json details!

**Pull request closed without merging**
