### PR TITLE
print null and undefined as blank

### PR DESCRIPTION
**Pull request by raine**

### CODE REVIEW

**Comment by stevenvachon** [comment]
@rauchg

**Comment by stevenvachon** [comment]
@TooTallNate

**Comment by whitelynx** [comment]
This fixes #65, right? Could this get merged and released?

**Comment by rauchg** [comment]
Thanks!

**Comment by pratikgala** [comment]
is this fix release to npm?

**Comment by raine** [comment]
> is this fix release to npm?

Probably not. https://github.com/gajus/table seems like decent replacement to `cli-table`

**Pull request merged**
