### PR TITLE
Add license file and field to package.json

### PR DESCRIPTION
**Pull request by igoradamenko**
Hey!

In this PR I've added LICENSE file and added a field to package.json describing the license.

It is important because different license-checking tools can't detect the license of this package properly due to absence of those things.

Hope I've made everything correctly and you would be able to publish a new version with those changes! 🐨

### CODE REVIEW

**Comment by igoradamenko** [comment]
@chrean, not sure who is able to merge this PR, so pinging you 🐱

**Review by chrean — APPROVED** [review]

**Comment by chrean** [comment]
Thank you @igoradamenko , approved and merged. This will be part of the new release.

**Comment by chrean** [comment]
Hi @igoradamenko , 

A PR is welcome.
We have reverted all changes on 0.3.x and we probably deleted the license field by accident.

**Comment by igoradamenko** [comment]
@chrean, ah, alright. Here is the PR: #163.

**Comment by chrean** [comment]
Thank you @igoradamenko , will review, merge and publish today. 🙇

**Pull request merged**
